[package]
name = "kvstore-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

tokio = { version = "1", features = ["full"]}
tonic = "0.11"
prost = "0.12"
tonic-reflection = "0.11"   # 👈 Add this line


[build-dependencies]

tonic-build = "0.11"
prost-build = "0.12"
